version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: 'achatdb'

    ports:
      - "3306:3306"

  spring_app:
    image: dhaferharbaoui/achat:1.0.0
    container_name: achat
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
           "spring.datasource.username" : "root",
           
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'